-- MAKE YOUR COLLEGE DATABASE 
CREATE DATABASE THAPAR;
-- DROP DATABASE THAPAR;
USE THAPAR;

CREATE TABLE students(
rollno INT PRIMARY KEY,
name varchar(50),
marks INT NOT NULL,
GRADE VARCHAR(1),
CITY  VARCHAR(10)

);
DROP TABLE students;

INSERT INTO students VALUES (37,"AVISEK",45,"B","BARASAT");
INSERT INTO students VALUES (18,"SHIVANSH",95,"A","SABJIMANDI");
INSERT INTO students VALUES (23,"MANAV",89,"A","MOHALI");
INSERT INTO students VALUES (49,"TUSHAR",20,"D","KOTHA");
INSERT INTO students VALUES (10,"SUBHAM",92,"A","BIHAR");
INSERT INTO students VALUES (12,"ALAPAN",78,"B","DURGAPUR");
SELECT name, marks FROM students;
SELECT DISTINCT CITY FROM students; /* DISTINCT USE FOR UNIQUE DONT REPEAT SAME CITY MORE THEN ONE TIME*/
SELECT * FROM students WHERE marks>80; 
/* where actually show what i want to see specially*/
SELECT * FROM students WHERE CITY= "BARASAT";
SELECT * FROM students WHERE marks+10 > 100; 

SELECT * FROM students;
