CREATE DATABASE IF NOT EXISTS COLLEGE;
USE COLLEGE;
CREATE TABLE EMPLOYEE (
ROLLNO INT PRIMARY KEY,
NAME VARCHAR(50),
AGE INT NOT NULL,
COUNTRY VARCHAR(50)
);
INSERT INTO EMPLOYEE VALUES (1, "AVISEK", 34,"INDIA");
INSERT INTO EMPLOYEE VALUES (2, "LAWRENCE",38,"CANADA");
INSERT INTO EMPLOYEE VALUES (3, "SAM", 56,"ENGLAND");
INSERT INTO EMPLOYEE VALUES (4, "QUERTINO", 37,"AUSTRALIA");
INSERT INTO EMPLOYEE VALUES (5, "JANG SINN", 29,"JAPAN");
SELECT * FROM EMPLOYEE;
